# Sales Data Overview

This notebook focuses on understanding the structure, columns,
and basic quality of the cleaned sales dataset before analysis.

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("C:/Users/MADHU/BTS FOREVER/BTS LOVE/sales_data_sample.xlsx")

In [4]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,Order_Date,Phone_no
0,10107,30,95.70,2,2871.00,Shipped,1,2,2003,Motorcycles,...,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,37676,2125557818
1,10121,34,81.35,5,2765.90,Shipped,2,5,2003,Motorcycles,...,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,37748,26471555
2,10134,41,94.74,2,3884.34,Shipped,3,7,2003,Motorcycles,...,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,37803,33146627555
3,10145,45,83.26,6,3746.70,Shipped,3,8,2003,Motorcycles,...,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,37858,6265557265
4,10159,49,100.00,14,5205.27,Shipped,4,10,2003,Motorcycles,...,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,37904,6505551386

In [5]:
df.shape

(2823, 25)

In [6]:
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE',
       'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'ADDRESSLINE1', 'ADDRESSLINE2',
       'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY',
       'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE', 'Order_Date',
       'Phone_no'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   STATUS            2823 non-null   str
 6   QTR_ID            2823 non-null   int64
 7   MONTH_ID          2823 non-null   int64
 8   YEAR_ID           2823 non-null   int64
 9   PRODUCTLINE       2823 non-null   str
 10  MSRP              2823 non-null   int64
 11  PRODUCTCODE       2823 non-null   str
 12  CUSTOMERNAME      2823 non-null   str
 13  ADDRESSLINE1      2823 non-null   str
 14  ADDRESSLINE2      302 non-null    str
 15  CITY              2823 non-null   str
 16  STATE             1337 non-null   str
 17  POSTALCODE        2747 non-null   str
 18  COUNTRY           2823 non-null   str
 19  TERRITORY         1749 non-null   str
 20  CONTACTLASTNAME   2823 non-null   str
 21  CONTACTFIRSTNAME  2823 non-null   str
 22  DEALSIZE          2823 non-null   str
 23  Order_Date        2823 non-null   int64
 24  Phone_no          2823 non-null   int64
dtypes: float64(2), int64(9), str(14)
memory usage: 551.5 KB

In [8]:
df.isna().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
Order_Date             0
Phone_no               0
dtype: int64

In [9]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP,Order_Date,Phone_no
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000,2823.000000,2.823000e+03
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551,38118.011690,1.802477e+10
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912,230.638153,8.789470e+10
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000,37627.000000,2.555467e+06
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000,37931.500000,6.522176e+08
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000,38153.000000,2.035553e+09
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000,38308.500000,5.145558e+09
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000,38503.000000,8.106634e+11

### Initial Observations

- Dataset contains sales transaction records.
- No major missing values in key business columns.
- Numeric columns such as sales and quantity are suitable for analysis.
- Dataset is clean and ready for exploratory data analysis.